/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package snakegame;

import java.awt.BorderLayout;
import java.awt.GridLayout;

import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JPanel;

public class App {

    public App() {
        // Create the main game window
        JFrame frame = new JFrame();
        JPanel panel = new JPanel();
        
        panel.setBorder(BorderFactory.createEmptyBorder(30, 30, 10, 30));
        panel.setLayout(new GridLayout(0, 1));

        frame.add(panel, BorderLayout.CENTER);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setTitle("Snake");
        frame.pack();
        frame.setVisible(true);
        frame.setSize(1280, 720);
    }

    public static void main(String[] args) {
        new App();
    }
}
